# Generated by Django 4.2.1 on 2024-06-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0002_alter_programme_dept_alter_volunteer_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(default="Pending for Approval", max_length=40),
        ),
    ]
