# Generated by Django 4.2.1 on 2024-06-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0003_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="roll_no",
            field=models.IntegerField(null=True),
        ),
    ]
