# Generated by Django 4.2.1 on 2024-06-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0004_alter_volunteer_roll_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="currentyear",
            field=models.IntegerField(default=1),
        ),
    ]
