# Generated by Django 4.2.1 on 2024-06-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0005_volunteer_currentyear"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteer",
            name="currentyear",
        ),
    ]
