# Generated by Django 4.2.1 on 2024-06-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0006_remove_volunteer_currentyear"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="unit",
            field=models.IntegerField(default=1),
        ),
    ]
