# Generated by Django 4.2.1 on 2024-06-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0007_volunteer_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="unit",
            field=models.IntegerField(),
        ),
    ]
