# Generated by Django 4.2.1 on 2024-06-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0008_alter_volunteer_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
    ]
