# Generated by Django 4.2.1 on 2024-06-14 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0009_volunteer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="volunteer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="nss.volunteer",
            ),
        ),
    ]
