# Generated by Django 5.0.6 on 2025-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0010_event_details_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='unit',
            field=models.IntegerField(choices=[(4, '4'), (5, '5'), (96, '96')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
