# Generated by Django 4.2.1 on 2024-06-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0010_alter_attendance_volunteer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="department",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="name",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="roll_no",
        ),
        migrations.AddField(
            model_name="attendance",
            name="no_of_hours",
            field=models.IntegerField(default=0),
        ),
    ]
