# Generated by Django 4.2.1 on 2024-06-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0011_remove_attendance_department_remove_attendance_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="no_of_hours",
            field=models.IntegerField(),
        ),
    ]
