# Generated by Django 4.2.1 on 2024-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0012_alter_attendance_no_of_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="totalhours",
            field=models.IntegerField(null=True),
        ),
    ]
