# Generated by Django 4.2.1 on 2024-06-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0013_volunteer_totalhours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteer",
            name="totalhours",
        ),
    ]
