# Generated by Django 5.0.6 on 2024-06-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0014_remove_volunteer_totalhours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("a+", "A+"),
                    ("a-", "A-"),
                    ("b+", "B+"),
                    ("b-", "B-"),
                    ("o+", "O+"),
                    ("o-", "O-"),
                    ("ab+", "AB+"),
                    ("ab-", "AB-"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="community",
            field=models.CharField(
                choices=[
                    ("st", "ST"),
                    ("sc", "SC"),
                    ("general", "General"),
                    ("obc", "OBC"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="unit",
            field=models.IntegerField(choices=[("1", "1"), ("2", "2"), ("3", "3")]),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="year",
            field=models.IntegerField(choices=[("1", "1"), ("2", "2"), ("3", "3")]),
        ),
        migrations.CreateModel(
            name="Attendance_status",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(default="pending for approval", max_length=30),
                ),
                (
                    "Event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nss.event"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attendance",
            name="Attendance_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="nss.attendance_status",
            ),
        ),
    ]
