# Generated by Django 5.0.6 on 2024-06-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0015_alter_volunteer_blood_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="Attendance_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nss.attendance_status"
            ),
        ),
    ]
