# Generated by Django 5.0.6 on 2024-06-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nss", "0016_alter_attendance_attendance_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance_status",
            old_name="Event",
            new_name="event",
        ),
    ]
